name: propertdia
description: "PROPERTDIA — Grow your investment. Real estate platform for Cambodia."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/partners/
    - assets/images/team/
    - assets/icons/home/
    - assets/icons/base/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
    - family: Google Sans Khmer
      fonts:
        - asset: assets/fonts/GoogleSansKhmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSansKhmer-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSansKhmer-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSansKhmer-Bold.ttf
          weight: 700
